# Generated by Django 5.1.3 on 2024-12-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_user_email_user_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=11111111111, max_length=11),
            preserve_default=False,
        ),
    ]
